### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by freeyland** [dockerwest/nginx-magento2#1]
I think there is a missing self signed certificate as the REST api of Magento does only work when there is a certificate available.
I've added it in the docker file and then it was working

**Comment by BlackIkeEagle** [comment]
From my experience the rest api worked just fine without ssl, you must ofcourse disable the forced ssl redirect in magento to have this work.

**Comment by BlackIkeEagle** [comment]
If you have added it, could you show it in a PR? I'm not saying it will be accepted, but it will be more clear what you have done

**Comment by BlackIkeEagle** [comment]
With the introduction of dockerwest/nginx, https support for all nginx images is now included

![Screenshot_20190926_225306](https://user-images.githubusercontent.com/293691/65724405-99295700-e0b0-11e9-9b8c-3b1837df3598.png)

how to add https: see https://github.com/dockerwest/nginx/blob/master/README.md#enable-https
